#!/bin/bash
function=`realpath scripts/sh/functions`
for f in "$function"/*.sh
do
    source "$f"
done
rnc=`realpath schema`
xsl=`realpath scripts/xsl`
java=`realpath scripts/java`
logiciels=`realpath scripts/logiciels`
treetagger=`realpath scripts/logiciels/treetagger/`
saxon="java -Xms1024m -Xmx2048m -jar scripts/logiciels/saxon-9.1.0.8j.jar"
alias rm='rm -f'
tbx="ressources/terminologies/termsuite"
