#!/bin/sh

# Set these paths appropriately

BIN=/home/smeoni/partage-Termith/scripts/logiciels/treetagger/bin
CMD=/home/smeoni/partage-Termith/scripts/logiciels/treetagger/cmd
LIB=/home/smeoni/partage-Termith/scripts/logiciels/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
